myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('siteBD.url')),
]

myproject/siteBD/forms.py
from django import forms

class LoginForm(forms.Form):
    email = forms.EmailField(max_length=255, label='Email')
    password = forms.CharField(max_length=255, widget=forms.PasswordInput(), label='Password')

class TipoEquipamentoForm(forms.Form):
    tipo = forms.CharField(max_length=255)

class AtributosForm(forms.Form):
    Atributo = forms.CharField(max_length=255)
    Descricao = forms.CharField(max_length=255)

class ValoresAtributosForm(forms.Form):
    Valor = forms.CharField(max_length=255)

class UtilizadoresForm(forms.Form):
    Username = forms.CharField(max_length=50)
    Password = forms.CharField(widget=forms.PasswordInput())
    Nome = forms.CharField(max_length=255)
    Email = forms.EmailField(max_length=255)
    Contacto = forms.CharField(max_length=20, required=False)
    ID_Perfil = forms.IntegerField()

class FornecedoresForm(forms.Form):
    Nome = forms.CharField(max_length=255)
    Morada = forms.CharField(max_length=255, required=False)
    Contacto = forms.CharField(max_length=20, required=False)
    NIF = forms.CharField(max_length=20)

class ArmazensForm(forms.Form):
    Localizacao = forms.CharField(max_length=255)

class ComponentesForm(forms.Form):
    Descricao = forms.CharField(max_length=255)
    Nome = forms.CharField(max_length=255)
    ID_Fornecedor = forms.IntegerField()

class EncomendaCompraForm(forms.Form):
    Estado = forms.CharField(max_length=255)
    Data = forms.DateField()
    ID_Utilizador = forms.IntegerField()
    ID_Fornecedor = forms.IntegerField()

class ComponentesEncomendaCompraForm(forms.Form):
    ID_Enc_compra = forms.IntegerField()
    ID_Comp = forms.IntegerField()
    Preco = forms.DecimalField(max_digits=10, decimal_places=2)
    Quantidade = forms.IntegerField()

class GuiaRemessaCompraForm(forms.Form):
    Data = forms.DateField()
    NIF = forms.CharField(max_length=20)
    ID_Enc_compra = forms.IntegerField()

class ComponentesGuiaRemessaCompraForm(forms.Form):
    ID_Remessa_compra = forms.IntegerField()
    ID_Comp = forms.IntegerField()
    Quantidade = forms.IntegerField()
    ID_Armazem = forms.IntegerField()

class MaoObraForm(forms.Form):
    Tipo = forms.CharField(max_length=255)
    Custo = forms.DecimalField(max_digits=10, decimal_places=2)

class EquipamentosForm(forms.Form):
    Nome = forms.CharField(max_length=255)
    Descricao = forms.CharField(max_length=255)
    Preco_Venda = forms.DecimalField(max_digits=10, decimal_places=2)
    Tipo_Equipamento = forms.IntegerField()

class FichaProducaoForm(forms.Form):
    ID_Mao_Obra = forms.IntegerField()
    Data_Hora_Inicio = forms.DateTimeField()
    Data_Hora_Fim = forms.DateTimeField()
    Quantidade = forms.IntegerField()
    ID_Armazem = forms.IntegerField()

class ComponentesFichaProducaoForm(forms.Form):
    ID_Ficha_prod = forms.IntegerField()
    ID_Comp = forms.IntegerField()
    Quantidade = forms.IntegerField()
    Custo_Final = forms.DecimalField(max_digits=10, decimal_places=2)
    ID_Armazem = forms.IntegerField()

class ClientesForm(forms.Form):
    Nome = forms.CharField(max_length=255)
    Morada = forms.CharField(max_length=255, required=False)
    Contacto = forms.CharField(max_length=20, required=False)
    NIF = forms.CharField(max_length=20)

class EncomendaVendaForm(forms.Form):
    ID_Utilizador = forms.IntegerField()
    ID_Cliente = forms.IntegerField()
    Estado = forms.CharField(max_length=255)
    Data = forms.DateField()

class EquipamentosEncomendaVendaForm(forms.Form):
    ID_Enc_Venda = forms.IntegerField()
    ID_Equipamento = forms.IntegerField()
    Preco_Total = forms.DecimalField(max_digits=10, decimal_places=2)
    Quantidade = forms.IntegerField()
    ID_Armazem = forms.IntegerField()

class GuiaRemessaVendaForm(forms.Form):
    ID_Enc_Venda = forms.IntegerField()
    Data = forms.DateField()
    NIF = forms.CharField(max_length=20)

class EquipamentosGuiaRemessaVendaForm(forms.Form):
    ID_Remessa_Venda = forms.IntegerField()
    ID_Equipamento = forms.IntegerField()
    Quantidade = forms.IntegerField()

class PerfilForm(forms.Form):
    Perfil = forms.CharField(max_length=100)
    Perms = forms.CharField(max_length=100)



myproject/siteBD/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import connection
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.urls import reverse_lazy
import json
from io import TextIOWrapper
from django.urls import reverse
from django.http import JsonResponse
from django.db import connections
from django.shortcuts import render, redirect
from .forms import EquipamentosForm

from myproject.database import valores_atributos_equipamentos_create, get_equipamento_by_id, update_by_id_equipamento, get_atributos_by_id_equipamento, delete_by_id_equipamento
from .forms import PerfilForm, UtilizadoresForm, ClientesForm, FichaProducaoForm, FornecedoresForm, MaoObraForm, ArmazensForm, ComponentesForm,TipoEquipamentoForm, EquipamentosForm
cursor = connection.cursor()

from django.db import connections

def get_database_connection(perms):
    if perms == 1:
        return connections['normal']
    else:
        return connections['default']


def check_user(username, password):
    try:
        with connection.cursor() as cursor:
            cursor.execute('SELECT check_user(%s, %s)', [username, password])
            user_exists = cursor.fetchone()[0]
        return user_exists
    except Exception as e:
        print(f"Error checking user: {e}")
        return False

def getperms(username):
    try:
        with connection.cursor() as cursor:
            cursor.execute('SELECT get_idperfil_by_username(%s)', [username])
            perms = cursor.fetchone()[0]
        return perms
    except Exception as e:
        print(f"Error checking perms: {e}")
        return 0

def getuserid(username):
    try:
        with connection.cursor() as cursor:
            cursor.execute('SELECT get_user_id(%s)', [username])
            id = cursor.fetchone()[0]
        return id
    except Exception as e:
        print(f"Error checking perms: {e}")
        return 0 

def login_user(request):
    username = request.session.get('username', None)
    perms = request.session.get('perms', None)
    if username is not None:
        return redirect('list_equipamentos') 
    if request.method == 'POST':
        username = request.POST['Username']
        password = request.POST['Password']
        
        user_exists = check_user(username, password)

        if user_exists:
            id=getuserid(username)
            perms=getperms(id)
            if(perms != 0):
                request.session['id']=id
                request.session['perms']=perms
                request.session['username']=username
            return redirect('list_utilizador')
        else:
            messages.success(request, "Erro ao realizar o login")
            return redirect('login')

    else:
        return render(request, 'login.html', {})
 
def logout_user(request):
    # Remove the username from the session
    if 'username' in request.session:
        del request.session['username']

    # Redirect to the login page or any other page you prefer
    return redirect('login')

def perfil(request):
    username = request.session.get('username', None)
    perms = request.session.get('perms', None)
    connection= get_database_connection(perms)
    if username is None:
        return redirect('login') 
    if (perms <2):
        return redirect('list_equipamentos')   
    if request.method == 'POST':
        form = PerfilForm(request.POST)
        if form.is_valid():  
            perfil = form.cleaned_data['Perfil']
            perms = form.cleaned_data['Perms']
            with connection.cursor() as cursor:
                cursor.execute('CALL sp_perfil_CREATE(%s, %s)', [perfil, perms])
            return redirect('list_perfil')  
    else:
        form = PerfilForm()

    try:
        with connection.cursor() as cursor:
            cursor.execute('SELECT * FROM fn_perfil_READALL()')
            data = cursor.fetchall()
    except Exception as e:
        print(f"Erro ao obter dados do banco de dados: {e}")
        data = []

    return render(request, 'perfis.html', {'form': form, 'data': data})

def editar_perfil(request, perfil_id):
    username = request.session.get('username', None)
    perms = request.session.get('perms', None)
    connection= get_database_connection(perms)
    try: 
        if username is None:
            return redirect('login') 
        if (perms <2):
            return redirect('list_equipamentos')  
        if request.method == 'POST':
            form = PerfilForm(request.POST)
            if form.is_valid():
                perfil = form.cleaned_data['Perfil']
                perms = form.cleaned_data['Perms']
                try:
                    with connection.cursor() as cursor:
                        cursor.execute('CALL sp_perfil_UPDATE(%s, %s, %s)', [perfil_id, perfil, perms])
                    return redirect('list_perfil')
                except Exception as e:
                    return redirect('list_perfil')
        else:
            pass
    except Exception as e:
        print(f"Error: {e}")
        return redirect('list_perfil')

def apagar_perfil(request, perfil_id):
    username = request.session.get('username', None)
    perms = request.session.get('perms', None)
    connection= get_database_connection(perms)
    try:
        if username is None:
            return redirect('login') 
        if (perms <2):
            return redirect('list_equipamentos')  
        with connection.cursor() as cursor:
            cursor.execute('CALL sp_perfil_DELETE(%s)', [perfil_id])
        return redirect('list_perfil')
    except Exception as e:
        # Handle exceptions here
        print(f"Error: {e}")
        return redirect('list_perfil')

def utilizador(request):
    username = request.session.get('username', None)
    perms = request.session.get('perms', None)
    connection= get_database_connection(perms)
    if username is None:
        return redirect('login') 
    if (perms <2):
        return redirect('list_equipamentos')   
    if request.method == 'POST':
            form = UtilizadoresForm(request.POST)
            if form.is_valid():  
                username = form.cleaned_data['Username']
                password = form.cleaned_data['Password']
                nome = form.cleaned_data['Nome']
                email = form.cleaned_data['Email']
                contacto = form.cleaned_data['Contacto']
                ID_Perfil = form.cleaned_data['ID_Perfil']
                with connection.cursor() as cursor:
                    cursor.execute('CALL sp_utilizadores_CREATE(%s, %s, %s, %s, %s, %s)',[username, password, nome, email, contacto, ID_Perfil])
                return redirect('list_utilizador')  
    else:
            form = UtilizadoresForm()

    try:
            with connection.cursor() as cursor:
                cursor.execute('SELECT * FROM View_Utilizador_Perfil')
                data = cursor.fetchall()
                cursor.execute('SELECT * FROM fn_perfil_READALL()')
                perfis = cursor.fetchall()
    except Exception as e:
            print(f"Erro ao obter dados do banco de dados: {e}")
            data = []
            perfis = []
    return render(request, 'utilizadores.html', {'form': form, 'data': data, 'perfis': perfis})

def editar_utilizador(request, utilizador_id):
    username = request.session.get('username', None)
    perms = request.session.get('perms', None)
    connection= get_database_connection(perms)
    try:
        if username is None:
            return redirect('login') 
        if (perms <2):
            return redirect('list_equipamentos')  
        if request.method == 'POST':
            form = UtilizadoresForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['Username']
                password = form.cleaned_data['Password']
                nome = form.cleaned_data['Nome']
                email = form.cleaned_data['Email']
                contacto = form.cleaned_data['Contacto']
                ID_Perfil = form.cleaned_data['ID_Perfil']
                try:
                    with connection.cursor() as cursor:
                        cursor.execute('CALL sp_utilizadores_UPDATE(%s, %s, %s, %s, %s, %s, %s)', [utilizador_id, username, password, nome, email, contacto, ID_Perfil])
                    return redirect('list_utilizador') 
                except Exception as e:
                    return redirect('list_utilizador')
        else:
            pass
    except Exception as e:
        print(f"Error: {e}")
        return redirect('list_utilizador') 

def apagar_utilizador(request, utilizador_id):
    username = request.session.get('username', None)
    perms = request.session.get('perms', None)
    connection= get_database_connection(perms)
    try:
        if username is None:
            return redirect('login') 
        if (perms <2):
            return redirect('list_equipamentos')  
        with connection.cursor() as cursor:
            cursor.execute('CALL sp_utilizadores_DELETE(%s)', [utilizador_id])
        return redirect('list_utilizador') 
    except Exception as e:
        print(f"Error: {e}")
        return redirect('list_utilizador') 

def cliente(request):
    username = request.session.get('username', None)
    perms = request.session.get('perms', None)
    connection= get_database_connection(perms)
    if username is None:
        return redirect('login') 
    if (perms <2):
        return redirect('list_equipamentos')   
    if request.method == 'POST':
        form = ClientesForm(request.POST)
        if form.is_valid():  
            nome = form.cleaned_data['Nome']

myproject/siteBD/templates/editar_equipamento.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <title>Equipamentos</title>
    <!-- Bootstrap CSS -->
    <style>
        .container {
            padding-top: 20px;
        }
        .scrollable-col {
            height: 75vh;
            overflow-y: auto;
        }
    </style>
</head>
<body>
        
    {% include 'navbar.html' %}

    <!-- Conteudo da pagina -->
    <div style="margin-left: 32px; margin-right: 32px; margin-top: 32px">
        <form method="post" class="row" id="editar-form">
            {% csrf_token %}
            {% for equipamento in detalhes %}
                <div class="col-6">  
                    <div class="d-flex justify-content-between align-items-center">
                        <h1>Editar Equipamento</h1>
                    </div>
                    <div class="form-group">
                        <label for="id_nome">Nome Equipamento:</label>
                        <input type="text" class="form-control" pattern="^(?!\s)(.*\S)?$" title="Não são permitidos espaços em branco no início ou no final." id="id_nome" name="Nome" value="{{ equipamento.1 }}" placeholder="Digite o nome do equipamento" required>
                    </div>
                    <div class="form-group">
                        <label for="id_tipo">Tipo Equipamento:</label>
                        <select class="form-control" required name="Tipo_Equipamento">
                            {% for tipo in tiposEquip %}
                                <option value="{{ tipo.0 }}">{{ tipo.1 }}</option>
                            {% empty %}
                                <option value="">Sem dados</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_preco">Preço:</label>
                        <input type="number" class="form-control" id="id_preco" value="{{equipamento.3}}" name="Preco_Venda" placeholder="Digite o preco" required>
                    </div>
                    <div class="form-group">
                        <label for="id_descricao">Descrição:</label>
                        <textarea style="height: 175px; resize: none;" class="form-control" rows="3" id="id_desc" name="Descricao" placeholder="Digite a descrição">{{equipamento.2}}</textarea>
                    </div>
                    <div class="d-flex justify-content-center" style="margin-top: 32px;">
                        <button type="submit" class="btn btn-danger ml-2" style="width: 50%;">Editar Equipamento</button>
                    </div>            
                </div>
            {% endfor %}
            <div class="col-6" id="atributos">
                <div class="d-flex justify-content-between align-items-center">
                    <h1>Especificações</h1>
                </div>
                {% for atributo, valor in equipamento.atributos.items %}
                    {% if atributo != "id" %}
                        <b><label for="{{ atributo }}">{{ atributo }}:</label></b>
                        {% if atributo in arrays %}
                            <div data-atributo="{{ atributo }}">
                                <ul data-atributo="{{ atributo }}" id="{{ atributo }}" style="padding: 0; list-style: none;">
                                    {% for item in valor %}
                                        <li style="padding: 0; list-style: none;">
                                            <input class="form-control" type="text" name="{{ atributo }}[]" value="{{ item }}">
                                            <button type="button" class="btn btn-dark remove-value-button" style="width: 50%; margin-top: 16px; margin-bottom: 16px;">Remover</button>
                                        </li>
                                    {% endfor %}
                                </ul>
                                <div class="text-center">
                                    <button type="button" class="btn btn-danger add-value-button mx-auto" style="width: 50%;" data-atributo="{{ atributo }}">Adicionar Valor</button>
                                </div>
                            </div>
                        {% else %}
                            <input class="form-control" type="text" name="{{ atributo }}" value="{{ valor }}">
                            <br>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                <div id="inputcont">
                </div>
                <button type="button" class="btn btn-dark w-50 mx-auto d-block" style="margin-top: 32px;" id="addInputButton">Adicionar Atributo</button>
            </div>
        </form>
    </div>

    <script>
        document.getElementById("addInputButton").addEventListener("click", function() {
            var container = document.getElementById("inputcont");
    
            var atributoInput = document.createElement("input");
            atributoInput.type = "text";
            atributoInput.name = "atributo_name";
            atributoInput.required = true;
            atributoInput.classList="form-control";
            atributoInput.placeholder="Digite o nome do atributo";
    
            var valorInput = document.createElement("input");
            valorInput.type = "text";
            valorInput.name = "valor";
            valorInput.required = true;
            valorInput.classList="form-control";
            valorInput.placeholder="Digite o valor do atributo (e.x: Amarelo,Vermelho,Azul)"
    
            container.appendChild(document.createElement("br"));
            container.appendChild(document.createTextNode("Nome aributo:"));
            container.appendChild(atributoInput);
            container.appendChild(document.createElement("br"));
            container.appendChild(document.createTextNode("Valor atributo:"));
            container.appendChild(valorInput);
        });

        document.addEventListener("DOMContentLoaded", function () {
            const form = document.getElementById("editar-form");

            form.addEventListener("click", function (e) {
                if (e.target.classList.contains("remove-value-button")) {
                    e.preventDefault();
                    const li = e.target.parentElement;
                    li.parentElement.removeChild(li);
                } else if (e.target.classList.contains("add-value-button")) {
                    e.preventDefault();
                    const atributo = e.target.getAttribute("data-atributo");

                    // Select the correct div first
                    const div = document.querySelector(`div[data-atributo="${atributo}"]`);

                    // Now, find the ul inside the div
                    const ul = div.querySelector(`ul[data-atributo="${atributo}"]`);

                    console.log("div:", div);
                    console.log("ul:", ul);
                    console.log("atributo:", atributo);

                    const templateButton = document.querySelector(".remove-value-button");
                    const removeButton = templateButton.cloneNode(true);
                    removeButton.textContent = "Remover";

                    const li = document.createElement("li");
                    const input = document.createElement("input");
                    input.type = "text";
                    input.name = atributo;
                    input.style.marginTop = "16px";
                    input.classList.add("form-control");
                    input.placeholder = "Novo Valor";

                    li.appendChild(input);
                    li.appendChild(removeButton);
                    ul.appendChild(li);
                }
            });
        });

    </script>
</body>
</html>

myproject/siteBD/templates/list_tipo_equipamento.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <title>Tipo de Equipamentos</title>
    <!-- Bootstrap CSS -->
    <style>
        .container {
            padding-top: 20px;
        }

    </style>
</head>
<body>
    
{% include 'navbar.html' %}

<!-- Conteúdo da página -->
<div style="margin-left: 32px; margin-right: 32px; margin-top: 32px">
    <!-- Caixa de pesquisa e botão "Novo Perfil" -->
    <div class="row sticky-top bg-white p-1">
        <div class="col-10">
            <div class="search-bar border"> 
                <span class="search-icon"><i class="fi fi-rr-search"></i></span>
                <input class="w-100" type="text" id="searchInput" placeholder="Pesquisar tipo de equipamento...">
            </div>      
        </div>
        <div class="col-2">
            <button type="button" class="btn btn-dark w-100 h-100" data-toggle="modal" data-target="#myModal">
              Novo Tipo de Equipamento
            </button>
        </div>
        </div>

    <!-- Tabela para exibir os tipos -->
    <table style="margin-top:32px" class="table table-bordered table-striped text-center" id="perfilTable"> <!-- Adicionando classe mx-auto para centralizar -->
        <thead class="text-center table-dark">
            <tr>
                <th style="width: 20%;">Tipo de Equipamento</th>
                <th style="width: 20%;">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for element in data %}
                <tr>
                    <td>{{ element.1 }}</td>
                    <td>
                        <button type="button" class="btn btn-dark btn-sm" style="width: 70px;" data-toggle="modal" data-target="#editarModal{{ element.0 }}">Editar</button>
                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" style="width: 70px;" data-target="#confirmDelete{{ element.0 }}">Eliminar</button>
                    </td>
                </tr>

                <!-- Modal para confirmação de eliminação -->
                <div class="modal fade" id="confirmDelete{{ element.0 }}" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="confirmDeleteLabel">Confirmar Eliminação</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Tem certeza de que deseja eliminar o tipo de equipamento "{{ element.1 }}"?</p>
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'delete_tipo_equipamento' element.0 %}" class="btn btn-danger">Eliminar</a> <!-- Link para a função de eliminar -->
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modal para editar tipo -->
                <div class="modal fade" id="editarModal{{ element.0 }}" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel{{ element.0 }}" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="editarModalLabel{{ element.0 }}">Editar tipo - {{ element.1 }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <!-- Formulário para editar o tipo -->
                                <form method="post" action="{% url 'edit_tipo_equipamento' element.0 %}">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_nome">Tipo:</label>
                                        <input type="text" value="{{ element.1 }}" class="form-control" pattern="^(?!\s)(.*\S)?$" title="Não são permitidos espaços em branco no início ou no final." required id="id_tipo" name="tipo" placeholder="Digite o tipo">
                                    </div>
                                    <button type="submit" class="float-right btn btn-dark">Editar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <tr>
                    <td colspan="12">Nenhum tipo de equipamento</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Modal para adicionar tipo -->
<div class="modal" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title">Criar tipo equipamento</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
              </button>
          </div>
          <div class="modal-body">
            
              <!-- Formulário para criar tipo -->
              <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_nome">Tipo:</label>
                    <input type="text" class="form-control" pattern="^(?!\s)(.*\S)?$" title="Não são permitidos espaços em branco no início ou no final." required id="id_tipo" name="tipo" placeholder="Digite o tipo">
                </div>
                <!-- Adicione mais campos conforme necessário -->
                <button class="float-right btn btn-dark" type="submit">Criar tipo equipamento</button>
            </form>
          </div>
      </div>
  </div>
</div>


  

<!-- Bootstrap JS e jQuery (recomendado para ser carregado ao final da página) -->
<script>
    $(document).ready(function () {
        // Captura o evento de digitar no campo de pesquisa
        $('#searchInput').on('keyup', function () {
            // Obtém o valor digitado
            var searchText = $(this).val().toLowerCase();

            // Filtra as linhas da tabela com base no valor digitado
            $('#perfilTable tbody tr').filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(searchText) > -1);
            });
        });
    });

</script>
</body>
</html>

myproject/siteBD/templates/navbar_logo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Navbar</title>
    <!-- Bootstrap CSS -->
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.0.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.0.0/uicons-bold-straight/css/uicons-bold-straight.css'>
    <style>
        .navcolor {
            background: linear-gradient(to right, #BD2A2E, #000000);
        }

        a {
            color: white;
            text-decoration: none;
        }

        .navcolor a:hover {
            color: white;
        }

    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navcolor">
        <a class="navbar-brand mr-auto logo" href="#">Computronix</a>
    </nav>
</body>
</html>